name: $pipeline_name
display_name: $pipeline_name
space_name: $SPACE_NAME
jenkins_integration_id: $jenkins_integration_id
description: ""
icon: ""
type: FROM_SCM
script: ""
script_path: Jenkinsfile
jenkins_integration_name: $jenkins_integration_name
triggers: []
template:
  uuid: $template_uuid
  arguments_values:
    containerInfo:
      clusterName: $REGION_NAME
      namespace: $K8S_NAMESPACE
      serviceName: $service_name
      containerName: $service_name
    command: ~
    args: ~
    image:
      registry: $REG_URL
      registryUUID: ""
      repository: $REPO_NAME
      repositoryUUID: ""
    imageTag: $imageTag
    env:
    - name: $envname
      value: $envvalue
    autoRollbackOnFail: true
    timeout: $time_out
namespace: $NAMESPACE