name: $pipeline_name
display_name: $pipeline_name
space_name: $SPACE_NAME
jenkins_integration_id: $jenkins_integration_id
description: ""
icon: ""
type: FROM_SCM
script: ""
script_path: Jenkinsfile
jenkins_integration_name: $jenkins_integration_name
triggers: []
template:
  uuid: $template_uuid
  arguments_values:
    sourceImage:
      registry: $source_reg_url
      registryUUID: ""
      repository: $source_repo
      repositoryUUID: ""
    sourceImageTag: $source_tag
    sourceImageRegistryCredentialsId: ""
    image:
      registry: $reg_url
      registryUUID: ""
      repository: $REPO_NAME
      repositoryUUID: ""
    imageTag: $tag
    imageRegistryCredentialsId: $REG_CREDENTIAL
namespace: $NAMESPACE