name: $pipeline_name
display_name: $pipeline_name
space_name: $PROJECT_NAME
jenkins_integration_id: $jenkins_integration_id
description: ""
icon: ""
type: FROM_SCM
script: ""
script_path: Jenkinsfile
jenkins_integration_name: $jenkins_integration_name
pipeline_scm:
  source: GIT
  repository_path: $GIT_REPO
  branch: $branch
  credential_name: $GIT_CREDENTIAL
triggers: []
template:
  uuid: $template_uuid
  arguments_values:
    sonarScanEnabled: false
    ciEnabled: false
    buildImageEnabled: false
namespace: $NAMESPACE