name: $pipeline_name
display_name: $pipeline_name
space_name: $PROJECT_NAME
jenkins_integration_id: $jenkins_integration_id
description: ""
icon: ""
type: FROM_SCM
script: ""
script_path: Jenkinsfile
jenkins_integration_name: $jenkins_integration_name
triggers: []
template:
  uuid: $template_uuid
  arguments_values:
    containerInfo:
      clusterName: $REGION_NAME
      namespace: $K8S_NAMESPACE
      applicationName: $service_name
      componentName: $service_name
      componentType: "Deployment"
      containerName: "containersname"
    command: ~
    args: ~
    image:
      registry: $REG_URL
      registryUUID: ""
      repository: $REPO_NAME
      repositoryUUID: ""
    imageTag: $imageTag
    timeout: $time_out
namespace: $NAMESPACE