name: $project
display_name: ""
description: ""
clusters:
- name: $REGION_NAME
  uuid: $REGION_ID
  service_type: "kubernetes"
  quota:
    cpu: 1111
    memory: 1111
    pvc_num: 1111
    pods: 1111
    storage: 1111
template: "empty-template"