pipeline: $pipeline_id
trigger: repository
data:
  type: repository
  registry: $REGISTRY
  repository: $REPO_NAME
  registry_uuid: $registry_uuid
  repository_uuid: $REPO_ID
  schedule_rule: ""
  image_tag: $image_tag
  auto_trigger_enabled: false
  active: true
namespace: $NAMESPACE