resource_actions:
- sync_config:trigger
- sync_config:update
- sync_config:view
- sync_config:create
- sync_config:delete
space_uuid: $SPACE_UUID
config_id: $CONFIG_ID
project_uuid: $PROJECT_UUID
dest:
- is_http: false
  username: ~
  endpoint: $ENDPOINT
  internal_id: $INTERNAL_ID
  dest_id: $DEST_ID
  dest_type: INTERNAL_REGISTRY
  password: ~
namespace: $NAMESPACE
source:
  info:
    repository_name: $REPO_NAME
    project_name: ~
    registry_name: $REGISTRY
config_name: $CONFIG_NAME
memory: $MEMORY
project_name: $PROJECT_NAME
space_name: $SPACE_NAME
cpu: 0.5